# Example parameters (customize as needed)
# Angles and increments in radians
pan_increment: 0.52
tilt_increment: 0.52
pan_range: [-1.57, 1.57]
tilt_range: [-1.57,1.57]
tilt_points: [0.0,-1.57,-1.05,-0.52,0.52,1.05]
image_topic: "/rgb_stereo_publisher/color/image"
depth_topic: "/rgb_stereo_publisher/stereo/depth"
pan_topic: "/mastcam_pan_controller/command"
tilt_topic: "/mastcam_tilt_controller/command"
